{"name": "test_01", "status": "broken", "statusDetails": {"message": "AttributeError: 'tuple' object has no attribute 'stdout'", "trace": "self = <Case.test_fio.TestIOzone object at 0x0000022AEB7CDE50>\n\n    def test_01(self):\n        rs = fp.send('ls -l')\n>       assert rs.stdout\nE       AttributeError: 'tuple' object has no attribute 'stdout'\n\ntest_fio.py:10: AttributeError"}, "start": 1740022966185, "stop": 1740022966498, "uuid": "8c4cbf12-604e-41e7-a756-862ad2b4d9be", "historyId": "01a55d7010f48ebe0c3cf2503891f546", "testCaseId": "01a55d7010f48ebe0c3cf2503891f546", "fullName": "Case.test_fio.TestIOzone#test_01", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_fio"}, {"name": "subSuite", "value": "TestIOzone"}, {"name": "host", "value": "Meiyi-EXT"}, {"name": "thread", "value": "25532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_fio"}]}