{"name": "test_02", "status": "broken", "statusDetails": {"message": "AttributeError: 'tuple' object has no attribute 'stdout'", "trace": "self = <Case.test_fio.TestIOzone object at 0x0000022AEB7CE350>\n\n    def test_02(self):\n        \"\"\"\n        \"\"\"\n        rs = fp.send('ls -l')\n>       assert rs.stdout\nE       AttributeError: 'tuple' object has no attribute 'stdout'\n\ntest_fio.py:16: AttributeError"}, "description": "\n        ", "start": 1740022966655, "stop": 1740022966810, "uuid": "e1ebcba4-0fc4-45d5-83ee-7dd2f0baf615", "historyId": "74076393987b829c40a76ca86a02226b", "testCaseId": "74076393987b829c40a76ca86a02226b", "fullName": "Case.test_fio.TestIOzone#test_02", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_fio"}, {"name": "subSuite", "value": "TestIOzone"}, {"name": "host", "value": "Meiyi-EXT"}, {"name": "thread", "value": "25532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_fio"}]}