{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <Case.test_fio.TestIOzone object at 0x0000026CED9BE350>\n\n    def test_02(self):\n        \"\"\"\n        \"\"\"\n        fp.send('ls -l')\n>       assert False\nE       assert False\n\ntest_fio.py:16: AssertionError"}, "description": "\n        ", "start": 1740022874258, "stop": 1740022874440, "uuid": "14611960-f790-40a8-b192-eb727074bb0a", "historyId": "74076393987b829c40a76ca86a02226b", "testCaseId": "74076393987b829c40a76ca86a02226b", "fullName": "Case.test_fio.TestIOzone#test_02", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_fio"}, {"name": "subSuite", "value": "TestIOzone"}, {"name": "host", "value": "Meiyi-EXT"}, {"name": "thread", "value": "1728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_fio"}]}