{"name": "test_01[iozone -r 1M -i 0 -i 1  -s 20G -I]", "status": "broken", "statusDetails": {"message": "ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。", "trace": "self = <Case.test_fio.TestIOzone object at 0x0000019E4FB99A90>\ncmd = 'iozone -r 1M -i 0 -i 1  -s 20G -I'\n\n    @pytest.mark.parametrize('cmd', [i[0] for i in data])\n    def test_01(self, cmd):\n>       ioz_res = fp.send(cmd)\n\ntest_fio.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\Utils\\Base_init.py:28: in send\n    stdin, stdout, stderr = self.ssh.exec_command(cmd)\nC:\\Users\\yi.mei-ext\\AppData\\Roaming\\Python\\Python313\\site-packages\\paramiko\\client.py:566: in exec_command\n    chan.exec_command(command)\nC:\\Users\\yi.mei-ext\\AppData\\Roaming\\Python\\Python313\\site-packages\\paramiko\\channel.py:70: in _check\n    return func(self, *args, **kwds)\nC:\\Users\\yi.mei-ext\\AppData\\Roaming\\Python\\Python313\\site-packages\\paramiko\\channel.py:255: in exec_command\n    self._wait_for_event()\nC:\\Users\\yi.mei-ext\\AppData\\Roaming\\Python\\Python313\\site-packages\\paramiko\\channel.py:1224: in _wait_for_event\n    raise e\nC:\\Users\\yi.mei-ext\\AppData\\Roaming\\Python\\Python313\\site-packages\\paramiko\\transport.py:2201: in run\n    ptype, m = self.packetizer.read_message()\nC:\\Users\\yi.mei-ext\\AppData\\Roaming\\Python\\Python313\\site-packages\\paramiko\\packet.py:496: in read_message\n    header = self.read_all(self.__block_size_in, check_rekey=True)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.packet.Packetizer object at 0x0000019E4FB33770>, n = 16\ncheck_rekey = True\n\n    def read_all(self, n, check_rekey=False):\n        \"\"\"\n        Read as close to N bytes as possible, blocking as long as necessary.\n    \n        :param int n: number of bytes to read\n        :return: the data read, as a `str`\n    \n        :raises:\n            ``EOFError`` -- if the socket was closed before all the bytes could\n            be read\n        \"\"\"\n        out = bytes()\n        # handle over-reading from reading the banner line\n        if len(self.__remainder) > 0:\n            out = self.__remainder[:n]\n            self.__remainder = self.__remainder[n:]\n            n -= len(out)\n        while n > 0:\n            got_timeout = False\n            if self.handshake_timed_out():\n                raise EOFError()\n            try:\n>               x = self.__socket.recv(n)\nE               ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。\n\nC:\\Users\\yi.mei-ext\\AppData\\Roaming\\Python\\Python313\\site-packages\\paramiko\\packet.py:322: ConnectionAbortedError"}, "attachments": [{"name": "log", "source": "b141557b-da7e-411f-a82d-cfe5a200f441-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "cmd", "value": "'iozone -r 1M -i 0 -i 1  -s 20G -I'"}], "start": 1740393128346, "stop": 1740393147307, "uuid": "14b8091f-43ac-4294-a4cf-ca0586143f61", "historyId": "1800ecaa154f528cbb1cc87e4fcc3d7a", "testCaseId": "01a55d7010f48ebe0c3cf2503891f546", "fullName": "Case.test_fio.TestIOzone#test_01", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_fio"}, {"name": "subSuite", "value": "TestIOzone"}, {"name": "host", "value": "Meiyi-EXT"}, {"name": "thread", "value": "16148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_fio"}]}